# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spicy/git/cs450

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spicy/git/cs450

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spicy/git/cs450/CMakeFiles /home/spicy/git/cs450//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spicy/git/cs450/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

Camera.o: Camera.cpp.o
.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

CarouselHorse.o: CarouselHorse.cpp.o
.PHONY : CarouselHorse.o

# target to build an object file
CarouselHorse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CarouselHorse.cpp.o
.PHONY : CarouselHorse.cpp.o

CarouselHorse.i: CarouselHorse.cpp.i
.PHONY : CarouselHorse.i

# target to preprocess a source file
CarouselHorse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CarouselHorse.cpp.i
.PHONY : CarouselHorse.cpp.i

CarouselHorse.s: CarouselHorse.cpp.s
.PHONY : CarouselHorse.s

# target to generate assembly for a file
CarouselHorse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/CarouselHorse.cpp.s
.PHONY : CarouselHorse.cpp.s

DisplayLists.o: DisplayLists.cpp.o
.PHONY : DisplayLists.o

# target to build an object file
DisplayLists.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DisplayLists.cpp.o
.PHONY : DisplayLists.cpp.o

DisplayLists.i: DisplayLists.cpp.i
.PHONY : DisplayLists.i

# target to preprocess a source file
DisplayLists.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DisplayLists.cpp.i
.PHONY : DisplayLists.cpp.i

DisplayLists.s: DisplayLists.cpp.s
.PHONY : DisplayLists.s

# target to generate assembly for a file
DisplayLists.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/DisplayLists.cpp.s
.PHONY : DisplayLists.cpp.s

Light.o: Light.cpp.o
.PHONY : Light.o

# target to build an object file
Light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Light.cpp.o
.PHONY : Light.cpp.o

Light.i: Light.cpp.i
.PHONY : Light.i

# target to preprocess a source file
Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Light.cpp.i
.PHONY : Light.cpp.i

Light.s: Light.cpp.s
.PHONY : Light.s

# target to generate assembly for a file
Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Light.cpp.s
.PHONY : Light.cpp.s

Menu.o: Menu.cpp.o
.PHONY : Menu.o

# target to build an object file
Menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Menu.cpp.o
.PHONY : Menu.cpp.o

Menu.i: Menu.cpp.i
.PHONY : Menu.i

# target to preprocess a source file
Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Menu.cpp.i
.PHONY : Menu.cpp.i

Menu.s: Menu.cpp.s
.PHONY : Menu.s

# target to generate assembly for a file
Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Menu.cpp.s
.PHONY : Menu.cpp.s

Scene.o: Scene.cpp.o
.PHONY : Scene.o

# target to build an object file
Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Scene.cpp.o
.PHONY : Scene.cpp.o

Scene.i: Scene.cpp.i
.PHONY : Scene.i

# target to preprocess a source file
Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Scene.cpp.i
.PHONY : Scene.cpp.i

Scene.s: Scene.cpp.s
.PHONY : Scene.s

# target to generate assembly for a file
Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Scene.cpp.s
.PHONY : Scene.cpp.s

World.o: World.cpp.o
.PHONY : World.o

# target to build an object file
World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/World.cpp.o
.PHONY : World.cpp.o

World.i: World.cpp.i
.PHONY : World.i

# target to preprocess a source file
World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/World.cpp.i
.PHONY : World.cpp.i

World.s: World.cpp.s
.PHONY : World.s

# target to generate assembly for a file
World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/World.cpp.s
.PHONY : World.cpp.s

bmptotexture.o: bmptotexture.cpp.o
.PHONY : bmptotexture.o

# target to build an object file
bmptotexture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bmptotexture.cpp.o
.PHONY : bmptotexture.cpp.o

bmptotexture.i: bmptotexture.cpp.i
.PHONY : bmptotexture.i

# target to preprocess a source file
bmptotexture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bmptotexture.cpp.i
.PHONY : bmptotexture.cpp.i

bmptotexture.s: bmptotexture.cpp.s
.PHONY : bmptotexture.s

# target to generate assembly for a file
bmptotexture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bmptotexture.cpp.s
.PHONY : bmptotexture.cpp.s

keytime.o: keytime.cpp.o
.PHONY : keytime.o

# target to build an object file
keytime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/keytime.cpp.o
.PHONY : keytime.cpp.o

keytime.i: keytime.cpp.i
.PHONY : keytime.i

# target to preprocess a source file
keytime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/keytime.cpp.i
.PHONY : keytime.cpp.i

keytime.s: keytime.cpp.s
.PHONY : keytime.s

# target to generate assembly for a file
keytime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/keytime.cpp.s
.PHONY : keytime.cpp.s

loadobjfile.o: loadobjfile.cpp.o
.PHONY : loadobjfile.o

# target to build an object file
loadobjfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/loadobjfile.cpp.o
.PHONY : loadobjfile.cpp.o

loadobjfile.i: loadobjfile.cpp.i
.PHONY : loadobjfile.i

# target to preprocess a source file
loadobjfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/loadobjfile.cpp.i
.PHONY : loadobjfile.cpp.i

loadobjfile.s: loadobjfile.cpp.s
.PHONY : loadobjfile.s

# target to generate assembly for a file
loadobjfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/loadobjfile.cpp.s
.PHONY : loadobjfile.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

material.o: material.cpp.o
.PHONY : material.o

# target to build an object file
material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/material.cpp.o
.PHONY : material.cpp.o

material.i: material.cpp.i
.PHONY : material.i

# target to preprocess a source file
material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/material.cpp.i
.PHONY : material.cpp.i

material.s: material.cpp.s
.PHONY : material.s

# target to generate assembly for a file
material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/material.cpp.s
.PHONY : material.cpp.s

osucone.o: osucone.cpp.o
.PHONY : osucone.o

# target to build an object file
osucone.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osucone.cpp.o
.PHONY : osucone.cpp.o

osucone.i: osucone.cpp.i
.PHONY : osucone.i

# target to preprocess a source file
osucone.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osucone.cpp.i
.PHONY : osucone.cpp.i

osucone.s: osucone.cpp.s
.PHONY : osucone.s

# target to generate assembly for a file
osucone.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osucone.cpp.s
.PHONY : osucone.cpp.s

osusphere.o: osusphere.cpp.o
.PHONY : osusphere.o

# target to build an object file
osusphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osusphere.cpp.o
.PHONY : osusphere.cpp.o

osusphere.i: osusphere.cpp.i
.PHONY : osusphere.i

# target to preprocess a source file
osusphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osusphere.cpp.i
.PHONY : osusphere.cpp.i

osusphere.s: osusphere.cpp.s
.PHONY : osusphere.s

# target to generate assembly for a file
osusphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osusphere.cpp.s
.PHONY : osusphere.cpp.s

osutorus.o: osutorus.cpp.o
.PHONY : osutorus.o

# target to build an object file
osutorus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osutorus.cpp.o
.PHONY : osutorus.cpp.o

osutorus.i: osutorus.cpp.i
.PHONY : osutorus.i

# target to preprocess a source file
osutorus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osutorus.cpp.i
.PHONY : osutorus.cpp.i

osutorus.s: osutorus.cpp.s
.PHONY : osutorus.s

# target to generate assembly for a file
osutorus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/osutorus.cpp.s
.PHONY : osutorus.cpp.s

plane.o: plane.cpp.o
.PHONY : plane.o

# target to build an object file
plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/plane.cpp.o
.PHONY : plane.cpp.o

plane.i: plane.cpp.i
.PHONY : plane.i

# target to preprocess a source file
plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/plane.cpp.i
.PHONY : plane.cpp.i

plane.s: plane.cpp.s
.PHONY : plane.s

# target to generate assembly for a file
plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/plane.cpp.s
.PHONY : plane.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.27.7/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... CarouselHorse.o"
	@echo "... CarouselHorse.i"
	@echo "... CarouselHorse.s"
	@echo "... DisplayLists.o"
	@echo "... DisplayLists.i"
	@echo "... DisplayLists.s"
	@echo "... Light.o"
	@echo "... Light.i"
	@echo "... Light.s"
	@echo "... Menu.o"
	@echo "... Menu.i"
	@echo "... Menu.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... World.o"
	@echo "... World.i"
	@echo "... World.s"
	@echo "... bmptotexture.o"
	@echo "... bmptotexture.i"
	@echo "... bmptotexture.s"
	@echo "... keytime.o"
	@echo "... keytime.i"
	@echo "... keytime.s"
	@echo "... loadobjfile.o"
	@echo "... loadobjfile.i"
	@echo "... loadobjfile.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... material.o"
	@echo "... material.i"
	@echo "... material.s"
	@echo "... osucone.o"
	@echo "... osucone.i"
	@echo "... osucone.s"
	@echo "... osusphere.o"
	@echo "... osusphere.i"
	@echo "... osusphere.s"
	@echo "... osutorus.o"
	@echo "... osutorus.i"
	@echo "... osutorus.s"
	@echo "... plane.o"
	@echo "... plane.i"
	@echo "... plane.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

